[tool.poetry]
name = "back2basicspider"
version = "0.1.0"
description = ""
authors = ["Mrnobody <mrcartoonster@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
